name: CI/CD Vue 4

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Upload production build artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist # Path to your built application