name: CI/CD Vue 3

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build application
        run: npm run build

      # - name: Upload production build artifact
      #   uses: actions/upload-pages-artifact@v4
      #   with:
      #     path: ./dist # Path to your built application